/**:
  ros__parameters:
    fcu_url: "udp://:14550@127.0.0.1:14551"
    gcs_url: ""
    target_system_id: 1
    target_component_id: 1
    system_time:
      time_ref_source: "fcu"
      timesync_mode: NONE
    plugin_allowlist:
      - 'sys_status'
      - 'sys_time'
      - 'imu'
      - 'command'
      - 'rc_io'
      - 'setpoint_velocity'
      - 'setpoint_position'
